
package de.fhbielefeld.swl.KINewsBoard.BusinessLayer.Authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://webservices.user.scl.fhbielefeld.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://webservices.user.scl.fhbielefeld.de/", className = "de.fhbielefeld.swl.KINewsBoard.BusinessLayer.Authentication.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://webservices.user.scl.fhbielefeld.de/", className = "de.fhbielefeld.swl.KINewsBoard.BusinessLayer.Authentication.LoginUserResponse")
    @Action(input = "http://webservices.user.scl.fhbielefeld.de/UserWebService/loginUserRequest", output = "http://webservices.user.scl.fhbielefeld.de/UserWebService/loginUserResponse")
    public String loginUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
