swagger: '2.0'
info:
  description: Analyzer Schnittstelle zum KI-NewsBoard.
  version: 1.0.0
  title: NewsBoard
basePath: /analyzer
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /news:
    get:
      summary: Liefert noch nicht analysierte News Einträge
      responses:
        200:
          description: Liste aller News Einträge
          schema:
            title: News Einträge
            type: array
            items:
              $ref: '#/definitions/News'
        401:
          description: Ungültiger Token
      security:
        - token: []
  /news/{newsId}:
    post:
      summary: Veröffentlich ein Analyse-Ergebnis zu einem News Eintrag
      parameters:
        - name: newsId
          in: path
          type: integer
          format: int32
          required: true
        - name: result
          in: body
          schema:
            $ref: '#/definitions/AnalyzeResult'
          required: true
      responses:
        200:
          description: Analyse Ergebnis angelegt
        400:
          description: Fehlerhafte Anfrage
        401:
          description: Ungültiger Token
      security:
        - token: []
securityDefinitions:
  token:
    description: |
      ** Token basierte Authentifizierung **


      Der Zugriff auf die Schnittstelle ist mit einem Token geschützt. Dieser kann durch den Administrator generiert werden.

      Der Token wird im Header der HTTP(S)-Anfrage übermitellt.
    type: apiKey
    name: token
    in: header
definitions:
  News:
    type: object
    properties:
      id:
        type: string
      crawler:
        type: object
        properties:
          id:
            type: integer
            format: int32
          name:
            type: string
      title:
        type: string
      image:
        type: string
      content:
        type: string
      source:
        type: string
      url:
        type: string
      date:
        type: string
        format: dateTime
  AnalyzeResult:
    type: object
    properties:
      newsId:
        type: integer
        format: int32
      value:
        type: integer
        format: int32
        minimum: -100
        maximum: 100
      sentences:
        type: array
        items:
          type: object
          properties:
            start:
              type: integer
              format: int32
            end:
              type: integer
              format: int32
            value:
              type: integer
              format: int32
              minimum: -100
              maximum: 100
