swagger: '2.0'
info:
  description: Frontend Schnittstelle zum KI-NewsBoard.
  version: 1.0.0
  title: NewsBoard
basePath: /frontend
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /news:
    get:
      summary: Liefert alle News Einträge
      description: >
        **Liefert News Einträge**
        
        
        Die zurückgegeben News Einträge werden auf 15 limitiert. Durch Angabe
        des Parameters 'page' können die nächsten 15 Einträge geladen werden.


        Die zurückzugebenden Einträge können durch die Angebe des Parameters
        'keyword' gefiltert werden.
      parameters:
        - name: page
          in: query
          description: Die gewünschte Seite die geladen werden soll.
          type: integer
          default: 1
          minimum: 1
        - name: keyword
          in: query
          description: Limitiert die Einträge auf die angegebenen Suchwörter.
          type: string
      responses:
        '200':
          description: Liste aller News Einträge
          schema:
            title: News Einträge
            type: array
            items:
              $ref: '#/definitions/News'
  '/news/findByViewId/{viewId}':
    get:
      summary: Liefert alle für eine View freigegeben News Einträge
      description: >
        ** Liefert alle News Einträge zu einer definierten View **


        Die zurückgegeben News Einträge werden auf 15 limitiert. Durch Angabe
        des Parameters 'page' können die nächsten 15 Einträge geladen werden.
      parameters:
        - name: viewId
          in: path
          description: Die gewünschte öffentliche Ansicht
          type: integer
          default: 1
          minimum: 1
          required: true
        - name: page
          in: query
          description: Die gewünschte Seite die geladen werden soll.
          type: integer
          default: 1
          minimum: 1
      responses:
        '200':
          description: Liste alle News Einträge für öffentliche Ansicht
          schema:
            type: array
            items:
              $ref: '#/definitions/News'
  '/news/{id}':
    get:
      summary: Liefert details zu einem News Eintrag
      description: >
        **Liefert alle details zu einem News Eintrag**


        Mit dem Parameter 'id' kann definiert werden, welcher News Eintrag
        angezeigt werden soll.
      parameters:
        - name: id
          in: path
          description: Die Id des gewünschten News Eintrags
          type: integer
          default: 1
          minimum: 1
          required: true
      responses:
        '200':
          description: Details des News Eintrags
          schema:
            $ref: '#/definitions/NewsDetails'
definitions:
  News:
    type: object
    properties:
      id:
        type: string
      crawler:
        type: object
        properties:
          id:
            type: integer
            format: int32
          name:
            type: string
      title:
        type: string
      image:
        type: string
      content:
        type: string
      source:
        type: string
      url:
        type: string
      date:
        type: string
        format: dateTime
  NewsDetails:
    type: object
    properties:
      news:
        $ref: '#/definitions/News'
      results:
        type: array
        items:
          type: object
          properties:
            analyzer:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
            value:
              type: integer
              format: int32
              minimum: -100
              maximum: 100
            sentences:
              type: array
              items:
                type: object
                properties:
                  start:
                    type: integer
                    format: int32
                  end:
                    type: integer
                    format: int32
                  value:
                    type: integer
                    format: int32
                    minimum: -100
                    maximum: 100
