swagger: '2.0'
info:
  description: Analyzer Schnittstelle zum KI-NewsBoard.
  version: 1.0.0
  title: NewsBoard
basePath: /analyzer
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /news:
    get:
      summary: Liefert News Einträge
      description: |
        **Liefert noch nicht analysierte News Einträge**


        Für die Abfrage der News Einträge wird ein Analyzer Authentifizierungs-Token benötigt.
      responses:
        '200':
          description: Liste aller News Einträge
          schema:
            title: News Einträge
            type: array
            items:
              $ref: '#/definitions/News'
      security:
        - api_token: []
  /result:
    post:
      summary: Veröffentlich ein Analyse-Ergebnis
      description: |
        ** Veröffentlicht Analyse Ergebnisse **


        Für das veröffentlichen von Analyse Ergebnissen wird ein Analyzer Authentifizierungs-Token benötigt.
      parameters:
        - name: result
          in: body
          schema:
            $ref: '#/definitions/AnalyzeResult'
          required: true
      responses:
        200:
          description: Analyse Ergebnis angelegt
      security:
        - api_token: []
securityDefinitions:
  api_token:
    type: apiKey
    name: api_token
    in: header
definitions:
  News:
    type: object
    properties:
      id:
        type: string
      crawler:
        type: object
        properties:
          id:
            type: integer
            format: int32
          name:
            type: string
      title:
        type: string
      image:
        type: string
      content:
        type: string
      source:
        type: string
      url:
        type: string
      date:
        type: string
        format: dateTime
  AnalyzeResult:
    type: object
    properties:
      newsId:
        type: integer
        format: int32
      value:
        type: integer
        format: int32
        minimum: -100
        maximum: 100
      sentences:
        type: array
        items:
          type: object
          properties:
            start:
              type: integer
              format: int32
            end:
              type: integer
              format: int32
            value:
              type: integer
              format: int32
              minimum: -100
              maximum: 100
